model:
  model_name_or_path: "eth-dl-rewards/internlm2-7b-mod"
  tokenizer_name_or_path: "internlm/internlm2-7b-reward"
  max_length: 1024
  already_reward_model: true
  lora:
    enable: true
    rank: 32
    alpha: 64
    target_modules: "all-linear"
    dropout: 0.01
    bias: "none"

dataset:
  datasets: 
    - name_or_path: "eth-dl-rewards/sft-data-math"
      split: "train"
      ratio: 1.0
  max_examples: 1000

huggingface:
  name: "eth-dl-rewards/internlm2-7b-sft-math-lora"
  push_to_hub: true

logging:
  wandb: true
  wandb_project: "train-sft"
  wandb_run_name: "internlm2-7b-sft-math-lora"
  wandb_entity: "eth-dl-rewards"
  run_group: "math"
  wandb_tags: ["math", "sft"]
  save_dir: "output"

train:
  gradient_accumulation_steps: 4
  gradient_checkpointing: false
  per_device_train_batch_size: 1
  lr_scheduler_type: "cosine"
  optimizer: "adamw_hf"
  epochs: 3
  max_steps: -1
  deepspeed_config_path: null
seed: 42