model:
  model_name_or_path: "internlm/internlm2-7b-reward"
  max_length: 4096
  lora:
    enable: true
    rank: 32
    alpha: 64
    target_modules: "all-linear"
    dropout: 0.01
    bias: "none"

dataset:
  datasets: 
    - name_or_path: "eth-dl-rewards/pref-data-math"
      split: "train"
      ratio: 1.0
  max_examples: 20000

huggingface:
  name: "eth-dl-rewards/internlm2-7b-reward-math"
  push_to_hub: true

logging:
  wandb: true
  wandb_project: "train-rm"
  wandb_run_name: "intern-lm-7b-reward-math-test"
  wandb_entity: "eth-dl-rewards"
  run_group: "math"
  wandb_tags: ["math", "20k"]
  save_dir: "output"

train:
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  per_device_train_batch_size: 4
  lr_scheduler_type: "cosine"
  optimizer: "adamw_hf"
  epochs: 1
  max_steps: -1
  deepspeed_config_path: null


seed: 42
