model:
  model_name_or_path: "meta-llama/Llama-3.1-8B-Instruct"
  temperature: 0.9
  max_length: 4096
  top_k: 10000
  top_p: 1.0
  max_num_seqs: 11

dataset:
  datasets:
    - name_or_path: "eth-dl-rewards/code-data-apps"
      split: "train"
      ratio: 1.0
  max_examples: 9500
  ground_truth_type: "code"

generation:
  num_samples_per_problem: 16
  prompt_template_path: "prompt_templates/code.txt"
  problems_per_batch: 100

huggingface:
  name: "eth-dl-rewards/pref-data-code"
  push_to_hub: true
  commit_message: "Added code data checkpoint"
  continue_from_checkpoint: true

logging:
  wandb: true
  wandb_project: "pref-data"
  wandb_run_name: "code-test-h100"
  wandb_entity: "eth-dl-rewards"
  run_group: "code"
  wandb_tags: ["code"]
  save_every: 1
  save_dir: "output"
  save_locally: true

preference:
  max_number_of_preferences_per_problem: 16

seed: 42