model:
  model_name_or_path: "eth-dl-rewards/internlm2-7b-reward-math-to-code-60k-sft"

dataset:
  datasets:
    - name_or_path: "eth-dl-rewards/pref-data-code"
      split: "eval"
      ratio: 1.0
  
  max_examples: 50000
  batch_size: 1

logging:
  wandb: true
  wandb_project: "eval-rm"
  wandb_run_name: "internlm2-7b-reward-math-to-code-60k-sft"
  wandb_entity: "eth-dl-rewards"
  run_group: "math->code"
  wandb_tags: ["math->code"]
  save_every: 1
  save_dir: "output"
  save_locally: true

seed: 42